apiVersion: sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: my-snazzy-policy
spec:
  images:
    - pattern: "*"
      authorities:
        - key:
            data: ---key---
---
apiVersion: sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: my-busted-policy
spec:
  images:
    - pattern: "*"
      authorities: 
        - key: {}
